"""add_incident_type_to_incident_record

Revision ID: f1e2d3c4b5a6
Revises: d3da32cf941c
Create Date: 2025-03-20 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f1e2d3c4b5a6"
down_revision = "d3da32cf941c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incidentrecord",
        sa.Column("incident_type", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incidentrecord", "incident_type")
    # ### end Alembic commands ###
